name        : bzip2
version     : 1.0.6
release     : 7
source      :
    - http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz : a2848f34fcd5d6cf47def00461fcb528a0484d8edef8208d6d2e2909dc61d9cd
homepage    : http://www.bzip.org
license     :
    - bzip2-1.0.6
summary     : High-quality block-sorting file compressor - utilities
description : |
    bzip2 is a freely available, patent free, high-quality data compressor. It typically compresses files to within 10% to 15% of the best available techniques, whilst being around twice as fast at compression and six times faster at decompression.
devel      : yes
autodep    : yes
optimize   : speed
setup      : |
    %patch -p1 < $pkgfiles/bzip2-1.0.6-install_docs-1.patch
    %patch < $pkgfiles/symlink.patch
    %patch < $pkgfiles/flags.patch
build      : |
    %make -f Makefile-libbz2_so
install    : |
    %make_install PREFIX=$installdir/usr
    install -d -m 00755 $installdir/%libdir%
    install -d -m 00755 $installdir/bin
    
    install -m 00755 libbz2.so.1.0.6 $installdir/%libdir%/
    ln -sv libbz2.so.1.0.6 $installdir/%libdir%/libbz2.so
    ln -sv libbz2.so.1.0.6 $installdir/%libdir%/libbz2.so.1
    ln -sv libbz2.so.1.0.6 $installdir/%libdir%/libbz2.so.1.0
    
    mv $installdir/usr/bin/* $installdir/bin/.
    rmdir $installdir/usr/bin
    mv $installdir/usr/man $installdir/usr/share/.
    
    # no static
    rm -rvf $installdir/usr/lib
